{% set name = "pyquil" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyquil-{{ version }}.tar.gz
  sha256: fbec8893115d1b831eb7b07a117ada6339506b8e4f7f7338f6e263a152fff7a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - matplotlib-inline >=0.1.6,<0.2.0
    - packaging >=23.1.0,<24.0.0
    - pydantic >=1.10.7,<2.0.0
    - qcs-sdk-python 0.12.2
    - tenacity >=8.2.2,<9.0.0
    - types-python-dateutil >=2.8.19,<3.0.0
    - types-retry >=0.9.9,<0.10.0
    - lark >=0.11.1,<0.12.0
    - networkx >=2.5
    - numpy >=1.22.0,<2.0.0
    - python >=3.8
    - qcs-api-client >=0.21.0,<0.22.0
    - rpcq >=3.10.0,<4.0.0
    - scipy >=1.7.3,<2.0.0
  run_constrained:
    - ipython >=7.21.0,<8.0.0

test:
  imports:
    - pyquil
    - pyquil._parser
    - pyquil.gates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library for quantum programming using Quil
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
    - BastianZim
