{% set name = "pyquil" %}
{% set version = "4.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rigetti/pyquil/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 02f086d2ff33b9974df28b57f27c4c269c468897732d6068dcdb1183b4065cc4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9,<4.0
  run:
    - quil >=0.11.2
    - deprecated >=1.2.14,<2.0.0
    - importlib-metadata >=3.7.3,<5
    - lark >=0.11.1,<0.12.0
    - matplotlib-inline <0.2.0,>=0.1.7
    - networkx >=2.5
    - numpy >=1.25.0,<2.0.0
    - packaging >=23.1.0,<24.0.0
    - python >=3.9,<4.0
    - qcs-api-client >=0.21.0,<0.22.0
    - qcs-sdk-python 0.19.2
    - rpcq >=3.11.0,<4.0.0
    - scipy >=1.11.0,<2.0.0
    - tenacity >=8.2.2,<9.0.0
    - types-deprecated >=1.2.9,<2.0.0
    - types-python-dateutil >=2.8.19,<3.0.0
    - types-retry >=0.9.9,<0.10.0
    - typing-extensions
  run_constrained:
    - ipython >=8.16.0,<9.0.0

test:
  imports:
    - pyquil
    - pyquil.gates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library for quantum programming using Quil
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - MementoRC
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
    - BastianZim
