{% set name = "pyquil" %}
{% set version = "3.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyquil-{{ version }}.tar.gz
  sha256: dfdbaa56842005030d48e1d18c9d29fbee4496d3b3116f7c0c9ce9851affdf38

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - tenacity >=8.2.2,<9.0.0
    - deprecated >=1.2.13,<2.0.0
    - types-deprecated >=1.2.9,<2.0.0
    - types-python-dateutil >=2.8.19,<3.0.0
    - types-retry >=0.9.9,<0.10.0
    - importlib-metadata >=3.7.3,<5
    - lark >=0.11.1,<0.12.0
    - networkx >=2.5.0,<3.0.0
    - numpy >=1.21.0,<2.0.0
    - python >=3.7,<4.0
    - qcs-api-client >=0.21.0,<0.22.0
    - retry >=0.9.2,<0.10.0
    - rpcq >=3.10.0,<4.0.0
    - scipy >=1.6.1,<2.0.0
  run_constrained:
    - ipython >=7.21.0,<8.0.0

test:
  imports:
    - pyquil
    - pyquil._parser
    - pyquil.gates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library for quantum programming using Quil
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
    - BastianZim
