{% set name = "pyquil" %}
{% set version = "4.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rigetti/pyquil/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b483cd00cf0788a12b15412e41aba1f8c3fc4b3ea34f05a88969136f1b775a12

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.9,<=3.14
  run:
    - networkx >=2.5
    - numpy >=1.25.0,<2.0.0
    - packaging >=23.1.0,<24.0.0
    - python >=3.9,<=3.14
    - qcs-sdk-python 0.17.9
    - rpcq >=3.11.0,<4.0.0
    - scipy >=1.11.0,<2.0.0
    - types-deprecated >=1.2.9,<2.0.0
  run_constrained:
    - ipython >=7.21.0,<8.0.0

test:
  imports:
    - pyquil
    - pyquil.gates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library for quantum programming using Quil
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - MementoRC
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
    - BastianZim
