{% set name = "pyquil" %}
{% set version = "4.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rigetti/pyquil/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b483cd00cf0788a12b15412e41aba1f8c3fc4b3ea34f05a88969136f1b775a12
  patches:
    - fix-python-3.21-req.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<3.13
  run:
    - deprecated >=1.2.14,<2.0.0
    - importlib-metadata >=3.7.3,<5
    - lark >=0.11.1,<0.12.0
    - matplotlib-inline <0.2.0,>=0.1.7
    - networkx >=2.5
    - numpy >=1.25.0,<2.0.0
    - packaging >=23.1.0,<24.0.0
    - python >=3.8,<3.13
    - qcs-api-client >=0.21.0,<0.22.0
    - qcs-sdk-python 0.17.9
    - rpcq >=3.11.0,<4.0.0
    - scipy >=1.11.0,<2.0.0
    - tenacity >=8.2.2,<9.0.0
    - types-deprecated >=1.2.9,<2.0.0
    - types-python-dateutil >=2.8.19,<3.0.0
    - types-retry >=0.9.9,<0.10.0
    - typing-extensions
  run_constrained:
    - ipython >=7.21.0,<8.0.0

test:
  imports:
    - pyquil
    - pyquil.gates
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library for quantum programming using Quil
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - MementoRC
    - jmackeyrigetti
    - kilimanjaro
    - notmgsk
    - BastianZim
