{% set name = "pyquil" %}
{% set version = "2.0.0" %}
{% set sha256 = "dbf13504e0fa5c34a625d61ebadf7b36f82e29646ca31baa43ab24b9d6d5cea7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pyquil-config-setup = pyquil.setup.pyquil_config_setup:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python
    - numpy
    - six
    - antlr-python-runtime
    - requests
    - contextvars
    - networkx
    - dataclasses
    - rpcq

test:
  imports:
    - pyquil
    - pyquil.gates

about:
  home: http://forest.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A Python library for quantum programming using Quil'
  doc_url: http://pyquil.readthedocs.io/en/latest/
  dev_url: https://github.com/rigetticomputing/pyquil

extra:
  recipe-maintainers:
    - mpharrigan
